version: "3.3"
services:
  test-service:
    image: test
    ports:
      - 8080:8080
    entrypoint: ["bash", "-c"]
    command:
      - |
        ./gradlew build
        java -jar ./build/libs/jpashop-0.0.1-SNAPSHOT.jar
        
    restart: always
    networks:
      - test

networks:
  test:
    external: true