version: "3.3"
services:
  springboot:
    image: springboot
    ports:
      - 8080:8080
    entrypoint: ["bash", "-c"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3307/db?useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_DATABASE_PLATFORM: org.hibernate.dialect.MySQL5Dialect
    command:
      - |
        sleep 20s
        java -jar app.jar
    restart: always
    
  database:
    image: mysql:5.7
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_TCP_PORT: 3307
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
